# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000, verbose_name='Real link')),
                ('bit_link', models.CharField(max_length=1000, verbose_name='Bit link')),
                ('count', models.IntegerField(default=0, verbose_name='Number of hits')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
    ]
