# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly_like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitlink',
            name='bit_link',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Bit link'),
        ),
        migrations.AlterField(
            model_name='bitlink',
            name='link',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Real link'),
        ),
    ]
