# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitly_like', '0002_auto_20171214_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitLink',
        ),
    ]
