# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly_like', '0004_auto_20171214_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitlink',
            name='link',
            field=models.URLField(verbose_name='Real link'),
        ),
    ]
