# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 15:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly_like', '0008_auto_20171215_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitlink',
            name='link',
            field=models.URLField(unique=True, validators=[django.core.validators.URLValidator], verbose_name=''),
        ),
    ]
