# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitly_like', '0009_auto_20171215_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitlink',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
